name = "drive"
type = "webpack"
workers_dev = true
account_id = "c2f36e419b8a983633887ea675dfba68"
zone_id = "069d1aef79f6a811760fe1b7251cd059"
kv_namespaces = [
    { binding = "BUCKET", id = "98a7e72e06354631ad57ff3ffe349887" }
]

[env.staging]
name = "drive-staging"

